config/routes.rb
Rails.application.routes.draw do
  root to: "catalogs#index"

  namespace :admin do
    get 'base/index'
    get '/add_publisher', to: 'publishers#new', as: 'add_publisher'

    resources :authors
    resources :books
    resources :publishers, except: [:new]
  end

  get '/signup', to: 'users#new', as: 'signup'
  get '/signin', to: 'sessions#new', as: 'signin'
  post '/signin', to: 'sessions#create'
  get 'reset_password', to: 'password_resets#new'
  get '/expired_token', to: 'password_resets#expired_token'



  resources :books, only: [:show]
  resources :users, only: [:index, :show, :new, :create]
  resource :session
  resources :catalogs, only: [:index, :show] do
    collection do
      post :search, to: 'catalogs#search'
    end
  end

  resources :carts, only: [:show, :destroy]
  resources :cart_items, only: [:create]
  resources :orders, only: [:new, :create]
  resources :password_resets, only: [:create, :edit, :update]

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :publisher
  has_many :publications, dependent: :destroy
  has_many :authors, through: :publications

  validates :title, presence: true
  validates :isbn, presence: true
  validates :description, presence: true
  validates :published_at, presence: true
  validates :publisher_id, presence: true
  validates :page_count, numericality: { only_integer: true, greater_than: 0 }
  validates :price, numericality: { greater_than_or_equal_to: 0.0 }

  mount_uploader :book_cover, BookCoverUploader

  def self.search_by_title(title)
    where('title LIKE ?', "%#{title}%").order(:title)
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < Admin::BaseController
	before_action :set_book, except:[:index, :new, :create]

	def index
		@books = Book.all
	end

	def show

	end

	def new
		@book = Book.new
		@publishers = Publisher.all
		@authors = Author.all
	end

	def create
		@book = Book.new(book_params)
		if @book.save
			flash[:success] = 'Book has been created'
			redirect_to [:admin, @book]
		else
			flash.now[:danger] = 'Book has not been created'
			@publishers = Publisher.all
			@authors = Author.all
			render :new
		end
	end

	def edit

	end

	def update
		if @book.update(book_params)
			flash[:success] = 'Book has been updated'
			redirect_to [:admin, @book]
		else
			flash[:danger] = "Book has not been updated" 
			render :edit
		end
	end

	def destroy
		if @book.destroy
			flash[:success] = 'Book has been deleted'
			redirect_to admin_books_path
		end
	end

	private

	def book_params
		params.require(:book).permit(:title, :isbn, :page_count, :price, :description, 
																 :published_at, :publisher_id, :book_cover, author_ids: [])
	end

	def set_book
		@book = Book.find(params[:id])
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :set_book, except:[:index, :new, :create]

	def index
		@books = Book.all
	end

	def show

	end

	def new
		@book = Book.new
		@publishers = Publisher.all
		@authors = Author.all
	end

	def create
		@book = Book.new(book_params)
		if @book.save
			flash[:success] = 'Book has been created'
			redirect_to @book
		else
			flash.now[:danger] = 'Book has not been created'
			@publishers = Publisher.all
			@authors = Author.all
			render :new
		end
	end

	def edit

	end

	def update
		if @book.update(book_params)
			flash[:success] = 'Book has been updated'
			redirect_to @book
		else
			flash[:danger] = "Book has not been updated" 
			render :edit
		end
	end

	def destroy
		if @book.destroy
			flash[:success] = 'Book has been deleted'
			redirect_to books_path
		end
	end

	private

	def book_params
		params.require(:book).permit(:title, :isbn, :page_count, :price, :description, 
																 :published_at, :publisher_id, :book_cover, author_ids: [])
	end

	def set_book
		@book = Book.find(params[:id])
	end
end

app/views/admin/books/_form.html.erb
<%= bootstrap_form_for([:admin, @book], :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Title</label>
    <div class='col-sm-9'>
      <%= f.text_field :title, class: 'form-control', hide_label: true, placeholder: 'Title of the book', autofocus: true %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Isbn</label>
    <div class='col-sm-9'>
      <%= f.text_field :isbn, class: 'form-control', hide_label: true, placeholder: 'Book ISBN' %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Page count</label>
    <div class='col-sm-9'>
      <%= f.text_field :page_count, class: 'form-control', hide_label: true, placeholder: 'Number of pages' %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Price</label>
    <div class='col-sm-9'>
      <%= f.text_field :price, class: 'form-control', hide_label: true, placeholder: 'Book unit price' %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Description</label>
    <div class='col-sm-9'>
      <%= f.text_area :description, class: 'form-control', hide_label: true, placeholder: 'Book description' %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Publication date</label>
    <div class='col-sm-9'>
      <%= f.text_field :published_at, placeholder: 'Date format: yyyy-mm-dd', class: 'form-control', hide_label: true %>
    </div>
  </div>

  <div class='form-group'>
    <label class='control-label col-sm-3'>Publisher</label>
    <div class='col-sm-9'>
      <%= f.select :publisher_id, @publishers.map { |p| [p.name, p.id] },
                      prompt: 'Select a publisher', class: 'form-control', hide_label: true %>
    </div>
  </div>

  <div class='form-group'>
    <label class='control-label col-sm-3'>Book cover</label>
    <div class='col-sm-9'>
      <%= f.file_field :book_cover, class: 'form-control', hide_label: true %>
    </div>
  </div>

  <div class='form-group'>
    <label class='control-label col-sm-3'>Authors</label>
    <div class='col-sm-9'>
      <%= f.collection_check_boxes :author_ids, @authors, :id, :full_name, class: 'form-control', hide_label: true %>
    </div>
  </div>

  <%# end %>
  <div class='form-group actions control-group'>
    <div class='col-sm-offset-3'>
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/admin/books/index.html.erb
<%= link_to "Add New Book", new_admin_book_path %>

app/views/admin/books/new.html.erb
<div class="row">
	<h3 class="text-center titles">Add New Book</h3>
</div>

<div class="row">
	<div class="col-md-12">
		<%= render "form" %>
	</div>
</div>