config/routes.rb
Rails.application.routes.draw do
  root to: "catalogs#index"

  namespace :admin do
    get 'base/index'
    get '/add_publisher', to: 'publishers#new', as: 'add_publisher'

    resources :authors
    resources :books
    resources :publishers, except: [:new]
  end

  get '/signup', to: 'users#new', as: 'signup'
  get '/signin', to: 'sessions#new', as: 'signin'
  post '/signin', to: 'sessions#create'
  get 'reset_password', to: 'password_resets#new'
  get '/expired_token', to: 'password_resets#expired_token'



  resources :books, only: [:show]
  resources :users, only: [:index, :show, :new, :create]
  resource :session
  resources :catalogs, only: [:index, :show] do
    collection do
      post :search, to: 'catalogs#search'
    end
  end

  resources :carts, only: [:show, :destroy]
  resources :cart_items, only: [:create]
  resources :orders, only: [:new, :create]
  resources :password_resets, only: [:create, :edit, :update]

end

app/views/shared/_footer.html.erb
<div class='container'>
	<div class='row'>
		<div class='col-md-10 col-md-offset-1'>
			<footer role="contentinfo">
				<p class="text-center"><small>Copyright &copy; Jason Vasquez</small></p>
			</footer>
		</div>
	</div>
</div>

app/views/shared/_header.html.erb
<header role="banner">
	<nav role="navigation" class="navbar navbar-default">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<%= link_to "Programstore App", root_path, class: "navbar-brand" %>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li class="active"><%= link_to "Home", root_path %></li>

					<%= form_tag(search_catalogs_path, class: "navbar-form navbar-left", role: "search") do %>
						<div class="form-group">
							<%= text_field_tag :search_word, nil, placeholder: "Search for books", class: "form-control" %>
						</div>
						<%= submit_tag "Search", class: "btn btn-default" %>
					<% end %>
					
					<li><%= link_to "Catalogs", catalogs_path %></li>
					<% if current_user && current_user.admin? %>
					<li><%= link_to "Authors", admin_authors_path %></li>
					<li><%= link_to "Publishers", admin_publishers_path %></li>
					<li><%= link_to "Books", admin_books_path %></li>
					<li><%= link_to "Users", users_path %></li>
					<% end %>
					
					<% unless current_user %>
						<li><%= link_to "Sign up", new_user_path %></li>
						<li><%= link_to "Sign in", signin_path %></li>
					<% else %>
						<li><%= link_to "Sign out", session_path, method: :delete %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</nav>
</header>

app/views/shared/_main.html.erb
<main role="main">
	<div class='container'>
		<%= render 'shared/messages' %>
		<div class='row'>

			<div class='col-md-9'>
				<% if content_for?(:sidebar) %>
					<div class='col-md-3'>
						<%= yield :sidebar %>
					</div>
					<div class='col-md-9'>
						<%= yield %>
					</div>
				<% else %>
					<div class='col-md-10 col-md-offset-1'>
						<%= yield %>
					</div>
				<% end %>
			</div>

			<div class='col-md-3'>
				<div id="cart">
					<%#= render @cart if @cart %>
				</div>
			</div>
		</div>
	</div>
</main>

app/views/shared/_messages.html.erb
<% flash.each do |name, msg| %>
	<div class='alert alert-<%="#{name}" %>'>
		<a href='#' class='close' data-dismiss='alert'>&#215;</a>
		<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
	</div>
<% end %>