config/routes.rb
Rails.application.routes.draw do
  root to: "catalogs#index"

  namespace :admin do
    get 'base/index'
    get '/add_publisher', to: 'publishers#new', as: 'add_publisher'

    resources :authors
    resources :books
    resources :publishers, except: [:new]
  end

  get '/signup', to: 'users#new', as: 'signup'
  get '/signin', to: 'sessions#new', as: 'signin'
  post '/signin', to: 'sessions#create'
  get 'reset_password', to: 'password_resets#new'
  get '/expired_token', to: 'password_resets#expired_token'



  resources :books, only: [:show]
  resources :users, only: [:index, :show, :new, :create]
  resource :session
  resources :catalogs, only: [:index, :show] do
    collection do
      post :search, to: 'catalogs#search'
    end
  end

  resources :carts, only: [:show, :destroy]
  resources :cart_items, only: [:create]
  resources :orders, only: [:new, :create]
  resources :password_resets, only: [:create, :edit, :update]

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :cart_items, dependent: :destroy
	has_many :books, through: :cart_items

	def add_book_to_items(book_id)
		cart_item = cart_items.where(book_id: book_id).first

		if cart_item.nil?
			book_price = Book.find(book_id).price 
			cart_item = cart_items.create(book_id: book_id, quantity: 1, price: book_price)
		else
			quantity = cart_item.quantity + 1
			cart_item.update(quantity: quantity)
			cart_item
		end
	end

	def total_sale
		sale = cart_items.map { |ci| ci.line_total }.reduce(:+)
		return 0.0 unless sale
		sale
	end

	def total_sale_in_cents
		(total_sale * 100).to_i
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_action :find_cart

	def show
	end

	def destroy
		@cart.destroy
		session[:cart_id] = nil
		redirect_to catalogs_path
	end

	private
	
	def find_cart
		@cart = Cart.find params[:id]
	end

end

app/views/carts/_cart.html.erb
<section>
	<div class='row'>
		<div class='col-md-10 col-md-offset-1'>
			<header>
				<h3 class='titles text-center' id='book-show'>Your Shopping Cart</h3>
			</header>

			<div id='cart-items'>
				<%= render cart.cart_items %>
			</div>
			<hr>
			<div id="cart-total">
				<strong>Total: </strong><%= number_to_currency(cart.total_sale || number_to_currency(item.line_total) %> )
				</div>
				<div class="row">
					<div id='clear-cart-btn' class="col-md-4">
					<%= button_to "Clear cart", cart_path(cart), method: :delete,
						data: { confirm: "Are you sure?"}, class: "btn btn-primary" %>
					</div>

					<div id="checkout-btn" class="col-md-4">
					<%= button_to "Checkout", new_order_path, method: :get, 
							class: "btn btn-default", id: "checkout" %>
					</div>
				</div>
				
			</div>
		</div>
	</div>
</section>

app/views/carts/show.html.erb
<section>
	<div class='row'>
		<div class='col-md-10 col-md-offset-1'>
			<header>
				<h3 class='titles text-center' id='book-show'>Your Shopping Cart</h3>
			</header>

			<% @cart.cart_items.each do |item|>
				<%= item.quantity %>&times;<%= item.book.title %><%= number_to_currency(item.line_total) %><br>
				<% end %>
				<hr>

				<strong>Total: </strong><%= number_to_currency(@cart.total_sale) %>

				<%= button_to "Clear cart", cart_path(@cart), method: :delete,
						data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
		</div>
	</div>
</section>