config/routes.rb
Rails.application.routes.draw do
  root to: "catalogs#index"

  namespace :admin do
    get 'base/index'
    get '/add_publisher', to: 'publishers#new', as: 'add_publisher'

    resources :authors
    resources :books
    resources :publishers, except: [:new]
  end

  get '/signup', to: 'users#new', as: 'signup'
  get '/signin', to: 'sessions#new', as: 'signin'
  post '/signin', to: 'sessions#create'
  get 'reset_password', to: 'password_resets#new'
  get '/expired_token', to: 'password_resets#expired_token'



  resources :books, only: [:show]
  resources :users, only: [:index, :show, :new, :create]
  resource :session
  resources :catalogs, only: [:index, :show] do
    collection do
      post :search, to: 'catalogs#search'
    end
  end

  resources :carts, only: [:show, :destroy]
  resources :cart_items, only: [:create]
  resources :orders, only: [:new, :create]
  resources :password_resets, only: [:create, :edit, :update]

end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
	has_many :books

	validates :name, presence: true
	validates :name, uniqueness: { case_sensitive: false }
end

app/controllers/admin/publishers_controller.rb
class Admin::PublishersController < Admin::BaseController
  before_action :require_signin
  before_action :require_admin
  before_action :set_publisher, except: [:index, :new, :create]

  def index
    @publishers = Publisher.all
  end

  def show
  end

  def new
    @publisher = Publisher.new
#    require 'pry'; binding.pry
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher.save
      flash[:success] = 'Publisher has been created.'
      redirect_to [:admin, @publisher]
    else
      flash[:danger] = 'Publisher has not been created.'
      render :new
    end
  end

  def edit
  end

  def update
    if @publisher.update(publisher_params)
      flash[:success] = 'Publisher has been updated.'
      redirect_to [:admin, @publisher]
    else
      flash[:danger] = 'Publisher has not been updated.'
      render :edit
    end
  end

  def destroy
    if @publisher.destroy
      flash[:success] = 'Publisher has been deleted.'
      redirect_to admin_publishers_path
    end
  end

  private
    def publisher_params
      params.require(:publisher).permit(:name)
    end

    def set_publisher
      @publisher = Publisher.find(params[:id])
    end
end

app/views/admin/publishers/_form.html.erb
<%= bootstrap_form_for([:admin, @publisher], :html => {:class => "form-horizontal"}) do |f| %>
	<div class='form-group'>
		<label for='name' class='control-label col-sm-3'>Name</label>
		<div class='col-sm-9'>
			<%= f.text_field :name, class: 'form-control', hide_label: true %>
		</div>
	</div>
	<div class='form-group actions control-group'>
		<div class='col-sm-offset-3'>
			<%= f.submit class: 'btn btn-primary' %>
		</div>
	</div>
	<% end %>

app/views/admin/publishers/edit.html.erb
<h3 class='titles'>Editing <%= "#{@publisher.name}" %></h3>
<div class='container'>
	<div class='row'>
		<div class='col-md-6'>
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/admin/publishers/index.html.erb
<section>
	<header>
		<% if @publishers.empty? %>
			<h3>No Publishers Defined</h3>
		<% else %>
			<h3>All Publishers</h3>
		<% end %>
	</header>
	<% @publishers.each do |publisher| %>
		<%= link_to publisher.name, [:admin, publisher] %></br>
	<% end %>
	<br>
	<p><%= link_to 'Add New publisher', admin_add_publisher_path, class: 'btn btn-primary' %></p>
	</section>

app/views/admin/publishers/new.html.erb
<h3 class='titles'> Adding New Publisher</h3>
<div class='row'>
  <div class='col-md-10 col-md-offset-1'>
    <%= render 'form' %>
  </div>
</div>

app/views/admin/publishers/show.html.erb
<section>
	<div class='row'>
		<div class='co-sm-10 col-sm-offset-1'>
			<header>
				<h3 class='titles'><%= "#{@publisher.name}" %>'s Details</h3>
			</header>
		</div>
	</div>
</section>

<% content_for(:sidebar) do %>
	Actions
	<hr class='sidebar-hr'>
	<ul class='sidebar-link'>
		<li><%= link_to 'Edit', [:edit, :admin, @publisher], class: 'btn btn-default btnwidth' %></li>
		<li><%= link_to 'Delete', [:admin, @publisher], method: :delete, class: 'btn btn-default bandwith' 
			data: { confirm: "Are you sure you want to delete #{@publisher.name}?"} %></li>
	</ul>
	<hr class='sidebar-hr'>
<% end %>